### ISSUE TITLE
async_pthread: Need pthread variant of daemon

### ISSUE THREAD

**Issue by adammoody** [ECP-VeloC/AXL#14]
The current daemon is launched as a separate process.  This is a design relic from SCR, where the process had been started and stopped externally to the SCR library.  I've tried to bury this logic inside of AXL, however, it's awkward to manage that process in AXL.  In particular, as written, one must be sure the path to the process executable is in the user's path before running.

A mcuh cleaner solution here would be to convert this daemon to a pthread.

**Comment by CamStan** [comment]
Did #42 fix this?

**Comment by tonyhutter** [comment]
Yep, closing issue
